### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by naul1** [VEVO/awsRetagger#13]
make build
<--snip-->
Code differs from gofmt's style
make: *** [fmt] Error 1

go fmt ./...
<--snip-->

make build
<--snip-->
make: *** [lint] Error 1

**Comment by aerostitch** [comment]
Hi @naul1,

Thanks for your report.
Sorry I just saw it, not sure why I didn't get notified months ago.
Anyway, I can't reproduce this error.
Could you tell me on which OS are you running the command please?
Also, could you send back the result of the following command-line please?
```
gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*") | wc -l
```

Thanks
Joseph
